# Generated by Django 5.1.1 on 2024-09-30 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_user'),
        ('courses', '0004_remove_courseprogress_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled_courses',
            field=models.ManyToManyField(through='courses.CourseProgress', to='courses.course'),
        ),
    ]
