# Generated by Django 5.1.1 on 2024-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('lectures', models.IntegerField()),
                ('level', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('reviews', models.IntegerField()),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('link', models.URLField()),
                ('enrollable', models.BooleanField(default=False)),
                ('platform', models.CharField(choices=[('udemy', 'Udemy'), ('coursera', 'Coursera'), ('edx', 'edX'), ('skillshare', 'Skillshare'), ('other', 'Other')], max_length=50)),
            ],
        ),
    ]
