# Generated by Django 5.1.1 on 2024-09-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch_name',
            field=models.CharField(default='Python Development', max_length=255),
            preserve_default=False,
        ),
    ]
