# Generated by Django 5.1.1 on 2024-10-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='wrong_answers',
            field=models.JSONField(null=True),
        ),
    ]
