INSERT INTO courses_module (course_id, title)
VALUES 
(1, 'Introduction to Python'),
(1, 'Python Functions'),
(1, 'Object-Oriented Programming in Python'),
(1, 'Working with Libraries'),
(1, 'File Handling in Python'),
(1, 'Error Handling and Exceptions'),
(1, 'Working with Databases'),
(1, 'Web Scraping with Python'),
(1, 'Testing in Python'),
(1, 'Final Project'),

(2, 'Introduction to Java'),
(2, 'Java Functions'),
(2, 'Object-Oriented Programming in Java'),
(2, 'Java Collections Framework'),
(2, 'File Handling in Java'),
(2, 'Error Handling and Exceptions'),
(2, 'Working with Databases'),
(2, 'Multithreading in Java'),
(2, 'Testing in Java'),
(2, 'Final Project'),

(3, 'Introduction to .NET'),
(3, 'C# Basics'),
(3, 'Object-Oriented Programming in .NET'),
(3, 'Working with ASP.NET'),
(3, 'File Handling in C#'),
(3, 'Error Handling and Exceptions in .NET'),
(3, 'Working with Databases in .NET'),
(3, 'LINQ in .NET'),
(3, 'Testing in .NET'),
(3, 'Final Project');
