INSERT INTO Skills (skills_name, skills_domain) VALUES
('Python Programming', 'Software Development'),
('Data Analysis', 'Data Science'),
('Machine Learning', 'Artificial Intelligence'),
('Web Development', 'Software Development'),
('Cloud Computing', 'Information Technology'),
('Project Management', 'Management'),
('Digital Marketing', 'Marketing'),
('UI/UX Design', 'Design'),
('Cybersecurity', 'Information Security'),
('Blockchain Technology', 'Information Technology'),
('Java Programming', 'Software Development'),
('Mobile App Development', 'Software Development'),
('Data Visualization', 'Data Science'),
('Networking', 'Information Technology'),
('SEO Optimization', 'Marketing'),
('Graphic Design', 'Design'),
('DevOps Practices', 'Software Development'),
('Game Development', 'Software Development'),
('Robotics', 'Engineering'),
('Big Data Technologies', 'Data Science');
